spring:
  profiles:
    active: ${active.profile}
    group:
      "local1": "local1, common"
      "local2": "local2, common"
      "dev1": "dev1, common"
      "dev2": "dev2, common"
---
spring:
  config:
    activate:
      on-profile: common
  messages:
    basename: errors
    encoding: UTF-8
  jpa:
    open-in-view: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        order_updates: true
        order_inserts: true
        jdbc.batch_size: 1000
        default_batch_fetch_size: 1000
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    #    org.hibernate.type: trace

jwt:
  header: Authorization
  secret: ${jwt.key}
  token-validity-in-seconds: ${jwt.time}

management:
  endpoints:
    web:
      exposure:
        include: "*"

file:
  path: ${file.path}
---
spring:
  config:
    activate:
      on-profile: local1
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: local2
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: dev1
  redis:
    host: redis
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: true
    hibernate:
      ddl-auto: none

  datasource:
    hikari:
      jdbc-url: ${jdbc.url}
      username: ${db.name}
      password: ${db.password}
      driver-class-name: org.mariadb.jdbc.Driver
server:
  port: 8081

logging:
  file:
    path: /var/log/app/
---
spring:
  config:
    activate:
      on-profile: dev2
  redis:
    host: redis
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: true
    hibernate:
      ddl-auto: none

  datasource:
    hikari:
      jdbc-url: ${jdbc.url}
      username: ${db.name}
      password: ${db.password}
      driver-class-name: org.mariadb.jdbc.Driver
server:
  port: 8082

logging:
  file:
    path: /var/log/app/
---